# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upfront < Formula
  desc "Force thinking before code — audit trail for AI-assisted feature definition"
  homepage "https://thinkupfront.dev"
  version "0.3.6"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.6/upfront_0.3.6_darwin_amd64.tar.gz"
      sha256 "8d46dadee321d255ecaa8ee556560901ee39f3dd40e85099d2639504895e5868"

      define_method(:install) do
        bin.install "upfront"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.6/upfront_0.3.6_darwin_arm64.tar.gz"
      sha256 "d1efd9440fc6c8aab5a22133e117188c88d891f7c6716d0c8bf698d3de50bbc9"

      define_method(:install) do
        bin.install "upfront"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.6/upfront_0.3.6_linux_amd64.tar.gz"
      sha256 "81935465b7125ea1290fdddc4143b01ab50b9cf581a2f5987a19b14548a10fa6"
      define_method(:install) do
        bin.install "upfront"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.6/upfront_0.3.6_linux_arm64.tar.gz"
      sha256 "7cf5fb4a9ad05deb48a4ae768f7ac186c1c3439982416a8c026ce12c150618e4"
      define_method(:install) do
        bin.install "upfront"
      end
    end
  end

  test do
    system "#{bin}/upfront", "status"
  end
end
