# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upfront < Formula
  desc "Force thinking before code — audit trail for AI-assisted feature definition"
  homepage "https://thinkupfront.dev"
  version "0.3.8"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.8/upfront_0.3.8_darwin_amd64.tar.gz"
      sha256 "b02a18c0cea703afb0bf734991087d8bf274e257c1beb33247feb2bc48920f64"

      define_method(:install) do
        bin.install "upfront"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.8/upfront_0.3.8_darwin_arm64.tar.gz"
      sha256 "9c580a7c1a0bd43fda7c682100dceced9c20555227c369244ffb8d129e4c8743"

      define_method(:install) do
        bin.install "upfront"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.8/upfront_0.3.8_linux_amd64.tar.gz"
      sha256 "4b5108808aa9142f3d4f5c4847fce1bc2d82981401e426c31424f904fc262aef"
      define_method(:install) do
        bin.install "upfront"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThinkUpfront/Upfront/releases/download/v0.3.8/upfront_0.3.8_linux_arm64.tar.gz"
      sha256 "d8c7f205b4307cd615826f8bfe81ab0e5299d8f5f947c4af8afffbc1a9341f71"
      define_method(:install) do
        bin.install "upfront"
      end
    end
  end

  test do
    system "#{bin}/upfront", "status"
  end
end
